name: Terraform Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t terraform-image:latest .

      - name: Save Docker Image
        run: |
          docker save terraform-image:latest -o terraform-image.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-image
          path: terraform-image.tar

  terraform-plan:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: terraform-image

      - name: Load Docker Image
        run: |
          docker load -i terraform-image.tar

      - name: Run Terraform Plan in Docker
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            terraform-image:latest terraform plan -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: terraform-image

      - name: Load Docker Image
        run: |
          docker load -i terraform-image.tar

      - name: Run Terraform Apply in Docker
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            terraform-image:latest terraform apply -auto-approve -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
